[package]
name = "kherrick/pwgen"
version = "1.0.15"
description = "A password generator compiled as Wasm that can be used from the command line, as a module, or custom element."
license = "AGPL-3.0"
repository = "https://github.com/kherrick/pwgen"

[[module]]
name = "pwgen"
source = "lib/pwgen.wasm"
abi = "emscripten"

[[command]]
name = "pwgen"
module = "pwgen"
